repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        args: ["check", "nunchaku", "comfyui", "examples", "tests", "--output-format", "github"]
  - repo: https://github.com/google/yapf
    rev: v0.43.0
    hooks:
      - id: yapf
        args: ["--diff", "--recursive", "nunchaku", "comfyui", "examples", "tests" ]
