name: pr_test

on:
  workflow_dispatch:

jobs:
  ping-runner:
    runs-on: self-hosted
    steps:
      - name: Check runner is online
        run: echo "Self-hosted runner is online!"
      - name: Test creating files
        run: touch a
