name: pr_test

on:
  workflow_dispatch:

jobs:
  ping-runner:
    runs-on: self-hosted
    steps:
      - name: Check runner is online
        run: echo "Self-hosted runner is online!"
  set-up-environment:
    runs-on: self-hosted
    needs: ping-runner
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # pulls submodules too
      - name: test where am i
        run: echo $PWD
