name: Check Self-hosted Runner

on:
  workflow_dispatch:

jobs:
  ping-runner:
    runs-on: Ubuntu20.04-test
    steps:
      - name: Check runner is online
        run: echo "Self-hosted runner is online!"
